# Note: file has same name as ALL group in inventory, so these vars will be used for all
#ansible_user: buyer
#ansible_password: DefaultPass1#
ansible_user: ccdc
ansible_password: ccdc

ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: ccdc

###################
# Secure
###################
secure_ansible_dir: "/ansible/red-teaming"
secure_redteam_pwd: "" # Doesn't really matter as pwd auth is disabled but still change it after downloading
secure_key_location: "/opt/inventory/id_ed25519.pub"
###################
# Siphon
###################
siphon_file_old_path: "/bin/bash"
siphon_file_new_path: "/bin/ash"
siphon_path: "/bin/siphon0"
siphon_logfile_path: "~/output_$TIMESTAMP" #TIMESTAMP is current system time in Y-M-D_H-M-S
siphon_server_ip: "{{ hostvars['siphoner_server']['ansible_host'] }}"
siphon_server_port: "920"

###################
# Doubletap
###################
doubletap_fuse_date: "2025-12-31"  # In format YYYY-MM-DD in America/New_York timezone
doubletap_fuse_time: "16:00:00"    # In format HH:MM:SS, using 24h time in America/New_York timezone
doubletap_fuse_armed: "false"      # true or false. Do not set to true unless you want to actually detonate for real!
doubletap_users: "user1 user2 user3" # Separated by spaces. Include the scored user and multiple other users for camo. Leave out at least 1 admin
doubletap_users_pwd: "R@nsomNot3"  # Password to set on the locked users
# ps1 loop
doubletap_ps1_loop_script_dest: "C:\\Windows\\Temp\\firewall_script1.ps1"
doubletap_ps1_loop_run_key_name: "DoubleTapScript"
doubletap_ps1_loop_log_path: "C:\\Windows\\Temp\\firewall_script1_log.txt"
# ps1 service
doubletap_ps1_service_script_dest: "C:\\Windows\\Temp\\firewall_script2.ps1"
doubletap_ps1_service_service_name: "DoubleTapScript"
doubletap_ps1_service_service_display_name: "DoubleTap Script"
doubletap_ps1_service_log_path: "C:\\Windows\\Temp\\firewall_script2_log.txt"
# ps1 task
doubletap_ps1_task_script_dest: "C:\\Windows\\Temp\\firewall_script1.ps1"
doubletap_ps1_task_task_name: "DoubleTapScript"
doubletap_ps1_task_log_path: "C:\\Windows\\Temp\\firewall_script3_log.txt"
# sh cron
doubletap_sh_cron_script_path: "/bin/doubletap1"
doubletap_sh_cron_job_name: "DoubleTapScript"
doubletap_sh_cron_job_user: "root"
doubletap_sh_cron_log_path: "/bin/doubletap1_log"
# sh loop
doubletap_sh_loop_script_path: "/bin/doubletap2"
doubletap_sh_loop_service_name: "Doubletap"
doubletap_sh_loop_log_path: "/bin/doubletap2_log"
# sh service
doubletap_sh_service_script_path: "/bin/doubletap3"
doubletap_sh_service_service_name: "DoubleTapScript"
doubletap_sh_service_service_description: "Double Tap Script"
doubletap_sh_service_log_path: "/bin/doubletap3_log"

###################
# Py C2
###################
pyc2_server_location: "/pyc2/pyc2-server.py"
pyc2_port: 9999
pyc2_port_range: 200
pyc2_server: "{{ hostvars['siphoner_server']['ansible_host'] }}"
pyc2_service_name: "pyc2"
pyc2_service_description: "pyc2"
pyc2_client_location_unix: "/pyc2-client.py"
pyc2_client_location_win: "C:\\Windows\\Temp\\pyc2-client.py"
pyc2_firewall_name: "Allow Update Services"
pyc2_debug: "True"
pyc2_buffer_size: 4096
pyc2_timeout_time: 15