# Note: file has same name as ALL group in inventory, so these vars will be used for all
#ansible_user: buyer
#ansible_password: DefaultPass1#
ansible_user: ccdc
ansible_password: ccdc

ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: ccdc