- name: Ping
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
  tags: 
    - all
    - ping

- name: Deploy Doubletap - Unix
  hosts: unix
  roles:
    - doubletap
  tags: 
    - all
    - doubletap
    - doubletap-unix

- name: Deploy Doubletap - Windows
  hosts: windows
  roles:
    - doubletap
  tags: 
    - all
    - doubletap
    - doubletap-windows

- name: Deploy Siphoner Clients - Ubuntu
  hosts: ubuntu
  roles:
    - siphoner-client
  tags: 
    - all
    - siphoner-client-ubuntu
    - siphoner-client

# Deploy server using Graylog Ansible Role
# https://github.com/Graylog2/graylog-ansible-role 
# https://galaxy.ansible.com/ui/standalone/roles/Graylog2/graylog/documentation/
# https://computingforgeeks.com/deploy-graylog-server-using-ansible-on-ubuntu-debian-centos/
# Install role:
# ansible-galaxy install graylog2.graylog
# Install dependencies (skip this, the install role should auto do it):
# ansible-galaxy install -r ~/.ansible/roles/graylog2.graylog/requirements.yml
# Then run this playbook.
- name: Install Graylog on Siphoner Server
  hosts: siphoner_server
  become: yes
  vars:
    graylog_version: 6.1
    graylog_install_java: True
    graylog_password_secret: "tKpLEv25yhbKaNXi1yw8jhq7xoAn2CZDYr02vtWvBY1bmj2PqMkbSTT8ADEQpFisMUcWu8kQpctC2kRuK66Rqrnc0UYpe2iV" # Insert your own here. Generate with: pwgen -s 96 1
    graylog_root_password_sha2: "bdc68a40521a2d24ec51b94f8359bc41e39325ea17e7df2f55d46e43bec887f2" # Insert your own root_password_sha2 here. Generate with:   echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_install_open_package: True
    graylog_install_enterprise_package: False
  roles:
    - graylog2.graylog
  tags:
    - "all"
    - "graylog"
    - "siphoner-server"

- name: Deploy Stabvest
  hosts: ubuntu
  roles:
    - stabvest
  tags:
    - all
    - stabvest