- name: Ping
  hosts: all
  gather_facts: no
  tasks:
    # Needs python on windows
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
  tags: 
    - all
    - ping

- name: Secure Jump Box(es)
  hosts: outofscope
  roles:
    - secure
  tags: 
    - all
    - secure

- name: Deploy Doubletap - Unix
  hosts: unix
  roles:
    - doubletap
  tags: 
    - all
    - doubletap
    - doubletap-unix

- name: Deploy Doubletap - Windows
  hosts: windows
  roles:
    - doubletap
  tags: 
    - all
    - doubletap
    - doubletap-windows

- name: Deploy Siphoner Clients - Ubuntu
  hosts: ubuntu
  roles:
    - siphoner-client
  tags: 
    - all
    - siphoner-client-ubuntu
    - siphoner-client

# Deploy server using Graylog Ansible Role
# https://github.com/Graylog2/graylog-ansible-role 
# https://galaxy.ansible.com/ui/standalone/roles/Graylog2/graylog/documentation/
# https://computingforgeeks.com/deploy-graylog-server-using-ansible-on-ubuntu-debian-centos/
# Install role:
# ansible-galaxy install graylog2.graylog
# Install dependencies (skip this, the install role should auto do it):
# ansible-galaxy install -r ~/.ansible/roles/graylog2.graylog/requirements.yml
# Then run this playbook.
- name: Install Graylog on Siphoner Server
  hosts: siphoner_server
  roles:
    - siphoner-server
  tags:
    - all
    - graylog
    - siphoner-server

- name: Deploy Stabvest
  hosts: stabvest_test
  roles:
    - stabvest
  tags:
    - all
    - stabvest

- name: Deploy pyc2 server
  hosts: siphoner-server
  roles:
    - py_c2-server
  tags:
    - all
    - pyc2
    - pyc2-server

- name: Deploy pyc2 clients windows
  hosts: windows
  roles:
    - py_c2-client
  tags:
    - all
    - pyc2
    - pyc2-clients
    - pyc2-clients-windows

- name: Deploy pyc2 clients unix
  hosts: unix
  roles:
    - py_c2-client
  tags:
    - all
    - pyc2
    - pyc2-clients
    - pyc2-clients-unix