---
- name: Gather system facts. Needed for OS architecture
  ansible.builtin.setup:

- name: Deploy ps1 via loop
  ansible.builtin.include_tasks: deploy_ps1-loop.yaml
  when: ansible_facts.os_family == "Windows"

- name: Deploy ps1 via custom service
  ansible.builtin.include_tasks: deploy_ps1-service.yaml
  when: ansible_facts.os_family == "Windows"

- name: Deploy ps1 via scheduled task
  ansible.builtin.include_tasks: deploy_ps1-task.yaml
  when: ansible_facts.os_family == "Windows"

# todo self delete for all are not working
- name: Deploy sh via cron
  ansible.builtin.include_tasks: deploy_sh-cron.yaml
  when: ansible_facts.os_family != "Windows"

# TODO this runs the script but does not produce log files
- name: Deploy sh via loop
  ansible.builtin.include_tasks: deploy_sh-loop.yaml
  when: ansible_facts.os_family != "Windows"

- name: Deploy sh via service
  ansible.builtin.include_tasks: deploy_sh-service.yaml
  when: ansible_facts.os_family != "Windows"