---
- name: Gather system facts. Needed for OS architecture
      ansible.builtin.setup:

- name: Deploy generic StabVest script (service-agnostic)
  ansible.builtin.include_tasks: deploy_generic.yml
  when: ansible_facts.os_family == "Debian"